### ISSUE TITLE
How to create other icons in SVG format

### ISSUE THREAD

**Issue by declan-haojin** [9inpachi/krit#10]
This is such an awesome template! Thanks for designing and making it really easy to customize. 

I was trying to add new icons such as new programming language icons but I don't know how to convert them into the SVG format that is consistent with those already there. For example, how did you remove the color from the SVG?

Thanks!

**Comment by 9inpachi** [comment]
Hey @declan-haojin,

Thanks for using the template.

I used icons from here: https://devicon.dev

You should be able to download them, place them in assets and import them like the other icons in this file: https://github.com/9inpachi/krit/blob/master/src/config/icons.js#L14

If that doesn't work, just let me know.

**Comment by declan-haojin** [comment]
Thanks!
