### ISSUE TITLE
How to put Project section between two custom sections?

### ISSUE THREAD

**Issue by declan-haojin** [9inpachi/krit#15]
By default, the project section appears first among all custom sections. However, is it possible to reposition the project section between two custom sections? For instance, I would like to have the about section appear first, followed by the project section, and then other custom sections. Thanks!

**Comment by 9inpachi** [comment]
Unfortunately, that's currently not possible. You could edit App.js to
place the projects section before the footer. I will try to make it more
configurable in the next few days so your use case works.

**Comment by declan-haojin** [comment]
Thank you!

**Comment by 9inpachi** [comment]
I have moved the projects section to the config file ([src/config/index.js](https://github.com/9inpachi/krit/blob/master/src/config/index.js)). Now you should be able to change the order of the sections in the `CustomSectionsConfig` array.

However, I wouldn't recommend using this project now. It's very outdated and the code in general is not good. I will most probably archive it in a couple of months.
