### ISSUE TITLE
After npm run start, it showing error

### ISSUE THREAD

**Issue by SANKARAMDAS** [9inpachi/krit#4]
Hi there, I clone your project and try improve some of the module but after npm run start, it's showing some error not able to solve it, Can you please check it once.
![2022-03-01 (4)](https://user-images.githubusercontent.com/31897843/156153866-4b505d67-0e9f-42f9-8416-0dc9514017bb.png)
.

**Comment by 9inpachi** [comment]
Hi,

Thanks a lot for pointing this out. I fixed it with the latest commit.

**Comment by SANKARAMDAS** [comment]
Thanks a lot. Really appreciate your work on this. Afterword if any issue
again occurs I'll let you know.

Again Thank You
